1. Дано: X*beta = y, , beta неизвестно.
2. Х = матрица значений независимой переменной, y = вектор значений зависимой переменной , beta = неизвестные коэффициенты (вектор с ними) для переменной x и свободный коэфф.
2. Мы хотим вычислить коэффициенты, умножив y на Х^-1 (inverse of X), так как:
3. X^-1 * X * beta = X^-1 * y
4. Произведение X^-1 * X = I (дает multiplicative identity matrix, то есть единицу, при умножении значения на которую, получаем то же самое значение, в примере - beta).
5. В этом случае остается: beta = X^-1 * y.
6. Однако, в нашем примере мы так напрямую умножить не можем,
т.к. матрицы X^-1 and y не подходят размерами.
7. Пользуемся свойством матриц: The inverse of Product
8. (A*B)^-1 = A^-1*B^-1
9. В выражении в пункте 1. выше домножаем обе части на X^T (X transpose), получаем:
10. X^T*X * beta = X^T * y
11. Выражаем beta (мы не можем разделить на матрицу/матрицы, но можем умножить на их inverse.
12. beta = X^T * y *(X^T * X)^-1
13. Выражение (X^T * X)^-1 равнозначно выражению (X^T) ^-1 * X^-1 по свойству в пункте 8.
14.  Следовательно, выражение в пункте 12 равнозначно выражению:
15. beta = X^T * y * (X^T)^-1*(X^-1) => beta = (X^T*(X^T)^-1)*y*(X^-1), => beta = I *y*X^-1 (где i = multiplicative identity matrix, а оставшееся выражение равнозначно выражению в пункте 5).
16. Вычисляем выражение в пункте 12 и получаем ответ: вектор значений коэффициентов beta.


In [ ]:
import numpy as np
from numpy.linalg import inv

In [ ]:
y= np.array( [[6], [5], [7], [10]])
X= np.array([[1, 1], [1, 2], [1, 3], [1, 4]])

X.shape

(4, 2)

In [ ]:
np.transpose(X)
np.transpose(X).shape

(2, 4)

Next, multiple X and its Transpose to get a square matrix.

In [ ]:
np.matmul(np.transpose(X), X)


array([[ 4, 10],
       [10, 30]])

Now that we have a square matrix, we can calculate its inverse.

In [ ]:
inv(np.matmul(np.transpose(X), X))

array([[ 1.5, -0.5],
       [-0.5,  0.2]])

Now we multiply the inverse we have by the Transpose of original X to receive a matrix
that is inverse of X and it has the dimensions (2, 4) that can be multiplied by matrix y (4, 1)

In [ ]:
np.matmul(inv(np.matmul(np.transpose(X), X)), np.transpose(X))

array([[ 1. ,  0.5,  0. , -0.5],
       [-0.3, -0.1,  0.1,  0.3]])

Now we can finally multiply y into the matrix that is inverse of X and of the appropriate dimensions to receive the coefficients we are looking for.

In [ ]:
np.matmul(np.matmul(inv(np.matmul(np.transpose(X), X)), np.transpose(X)), y)

array([[3.5],
       [1.4]])